spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://;databaseName=prueba
    username: phm
    password: 2022phm

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      database: prueba
      host: localhost
#       port: 28001 # Puerto servidor con sharding
      port: 27017

  mongodb:
    embedded:
      version: 6.0

logging:
  level:
    org.springframework.data: DEBUG
    org.mongodb.driver.protocol.command: DEBUG