spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://;databaseName=prueba
    username: phm
    password: 2022phm

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    mongodb:
      database: prueba
      host: localhost
#       port: 28001 # Puerto servidor con sharding
      port: 27017

  mongodb:
    embedded:
      version: 6.0
#      TODO: Desactivar? vvv
  main:
    allow-bean-definition-overriding: true
  neo4j:
    authentication:
      username: neo4j
      password: phm2022
    uri: bolt://localhost:7687

logging:
  level:
    org.springframework.data: DEBUG
    org.mongodb.driver.protocol.command: INFO
    org.neo4j: DEBUG